# Cloud Build configuration for building and pushing the GPT-OSS Responses image.
# Use scripts/cloud_build.sh to submit builds with sensible defaults.

substitutions:
  _IMAGE_URI: "us-docker.pkg.dev/focused-sentry-442212-q8/gptoss-120-server/gptoss-mxfp4"
  _IMAGE_TAG: "local"

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

timeout: 3600s

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-t"
      - "${_IMAGE_URI}:${_IMAGE_TAG}"
      - "-t"
      - "${_IMAGE_URI}:latest"
      - .

images:
  - "${_IMAGE_URI}:${_IMAGE_TAG}"
  - "${_IMAGE_URI}:latest"
