[workspace]
authors = ["daver987 <info@drobertson.pro>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "gptoss-120-server"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
test = "pytest"

[dependencies]
python = ">=3.13.7,<3.14"
fastapi = ">=0.117.1,<0.118"
uvicorn = ">=0.37.0,<0.38"
transformers = ">=4.56.2,<5"
pytest = ">=8.4.2,<9"
httpx = ">=0.28.1,<0.29"
"mojo" = "<1.0.0"
