[workspace]
authors = ["daver987 <info@drobertson.pro>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "gptoss-120-server"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
test = "pytest"

[dependencies]
python = ">=3.11,<3.13"
fastapi = "0.115.*"
uvicorn = "0.30.*"
transformers = ">=4.43"
pytest = ">=8.3"
httpx = ">=0.27"
"mojo" = "<1.0.0"
